export interface Screener {
  eps: string,
  marketcap: string,
  shares: string,
  peratio: string,
  roeratio: string,
  dividend: string,
  dividendyield: string,
  nta: string,
  parvalue: string,
  price:string,
  volume: string,
  unusualVolume: string,
  sma20: string,
  sma50: string,
  rsi: string,
  gap: string,
  atr: string,
  vwap: string,
}
